trigger:
- main

pool:
  name: 'Default'
  vmImage: 'windows-latest'
steps:
- task: Gradle@3
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew.bat'
    gradleOptions: '-Xmx3072m --debug'
    javaHomeOption: 'Path'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
