trigger:
- main

pool:
  name: 'Default'
  vmImage: 'windows-latest'

steps:
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-21"
    echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME)\bin;$(PATH)"
  displayName: 'Set JAVA_HOME and PATH'

- task: Gradle@3
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew.bat'
    gradleOptions: '-Xmx3072m --debug'
    javaHomeOption: 'JDKVersion'  # Automatically select a JDK version
    jdkVersionOption: '21'         # Specify the JDK version
    jdkArchitectureOption: 'x64'   # Specify the JDK architecture
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
