trigger:
- main

pool:
  name: 'Default'
  vmImage: 'windows-latest'
steps:
- task: Gradle@3
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
