trigger:
  branches:
    include:
      - main  # Or your branch

pool:
  name: Default  # Use the self-hosted agent

steps:
- script: |
    echo Starting pre-tasks
  displayName: 'Run Pre-Tasks'

- script: |
    echo Deleting package-lock.json
    if exist package-lock.json del package-lock.json
    echo Installing npm dependencies
    npm install
  displayName: 'Delete package-lock.json and Install Dependencies'

- script: |
    echo Navigating to android directory
    cd android
    echo Running gradlew.bat clean and assembleRelease
    gradlew.bat clean
    gradlew.bat assembleRelease
  displayName: 'Build Android Release APK'

- task: CopyFiles@2
  inputs:
    contents: 'android/app/build/outputs/apk/release/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy APK to Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish APK as Build Artifact'
