trigger:
- main

pool:
  name: 'Default'
  vmImage: 'windows-latest'

steps:
- task: Gradle@3
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'  # Explicit path to gradlew
    options: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersion: '1.8'
    jdkArchitecture: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
